const channels = {
  all: { leads: 200, cpl: '$86', conversion: '12.8%', roas: '3.6x', note: '+28.4% vs. periodo anterior', bars: [55, 75, 40, 63] },
  paid: { leads: 143, cpl: '$91', conversion: '10.4%', roas: '3.1x', note: 'Vista filtrada · Meta + Google', bars: [67, 86, 18, 42] },
  organic: { leads: 39, cpl: '$31', conversion: '18.2%', roas: '5.4x', note: 'Vista filtrada · SEO', bars: [25, 34, 92, 30] },
  retention: { leads: 18, cpl: '$23', conversion: '26.1%', roas: '6.2x', note: 'Vista filtrada · Email', bars: [20, 25, 38, 94] }
};
const campaigns = [['Google Ads', 4800, 92, 52, 'Escalar'], ['Meta Ads', 5600, 51, 110, 'Optimizar'], ['SEO', 1200, 39, 31, 'Sostener'], ['Email', 420, 18, 23, 'Expandir']];
function setupTheme() { const button = document.querySelector('#theme-toggle'); const apply = (theme) => { document.body.dataset.theme = theme; button.querySelector('.theme-label').textContent = theme === 'dark' ? 'Claro' : 'Oscuro'; button.setAttribute('aria-pressed', String(theme === 'dark')); }; apply(localStorage.getItem('portfolio-demo-theme') || 'light'); button.addEventListener('click', () => { const next = document.body.dataset.theme === 'dark' ? 'light' : 'dark'; localStorage.setItem('portfolio-demo-theme', next); apply(next); }); }
function notify(message) { const node = document.createElement('div'); node.className = 'toast'; node.textContent = message; document.body.appendChild(node); setTimeout(() => node.remove(), 1800); }
function copyText(value) { if (navigator.clipboard?.writeText) return navigator.clipboard.writeText(value); const area = document.createElement('textarea'); area.value = value; document.body.appendChild(area); area.select(); document.execCommand('copy'); area.remove(); return Promise.resolve(); }
function updateDashboard(key) { const data = channels[key]; document.querySelectorAll('[data-channel]').forEach((item) => item.classList.toggle('active', item.dataset.channel === key)); document.querySelector('#leads').textContent = data.leads; document.querySelector('#cpl').textContent = data.cpl; document.querySelector('#conversion').textContent = data.conversion; document.querySelector('#roas').textContent = data.roas; document.querySelector('#leads-note').textContent = data.note; document.querySelector('#growth').textContent = key === 'all' ? '+28.4%' : 'escenario'; document.querySelectorAll('#bars i').forEach((bar, index) => { bar.style.height = `${data.bars[index]}%`; }); }
function buildUtm() { const base = document.querySelector('#base-url').value.trim(); const source = document.querySelector('#utm-source').value.trim(); const medium = document.querySelector('#utm-medium').value.trim(); const campaign = document.querySelector('#utm-campaign').value.trim(); if (!base || !source || !medium || !campaign) throw new Error('Completa todos los campos UTM'); try { new URL(base); } catch { throw new Error('La URL base no es válida'); } const separator = base.includes('?') ? '&' : '?'; return `${base}${separator}utm_source=${encodeURIComponent(source)}&utm_medium=${encodeURIComponent(medium)}&utm_campaign=${encodeURIComponent(campaign)}`; }
function exportMix() { const csv = ['canal,inversion,leads,cpl,estado', ...campaigns.map((row) => row.join(','))].join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([`\ufeff${csv}`], { type: 'text/csv' })); link.download = 'marketing-campaign-mix.csv'; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 0); notify('Campaign mix exportado'); }
document.querySelectorAll('[data-channel]').forEach((button) => button.addEventListener('click', () => updateDashboard(button.dataset.channel)));
document.querySelector('#date-range').addEventListener('change', (event) => { document.querySelector('.chart-card small').textContent = event.target.selectedOptions[0].textContent + ' · datos demostrativos'; notify(`Periodo: ${event.target.selectedOptions[0].textContent}`); });
document.querySelector('#export-mix').addEventListener('click', exportMix);
document.querySelector('#utm-form').addEventListener('submit', (event) => { event.preventDefault(); try { document.querySelector('#utm-result').textContent = buildUtm(); notify('UTM generado'); } catch (error) { notify(error.message); } });
document.querySelector('#copy-utm').addEventListener('click', async () => { try { const url = buildUtm(); document.querySelector('#utm-result').textContent = url; await copyText(url); notify('UTM copiado'); } catch (error) { notify(error.message); } });
const experiments = JSON.parse(localStorage.getItem('marketing-experiments') || '{}'); document.querySelectorAll('.experiment-toggle').forEach((button) => { const key = button.dataset.experiment; const refresh = () => { button.textContent = experiments[key] ? 'En prueba ✓' : 'Marcar en prueba'; button.classList.toggle('done', Boolean(experiments[key])); }; button.addEventListener('click', () => { experiments[key] = !experiments[key]; localStorage.setItem('marketing-experiments', JSON.stringify(experiments)); refresh(); notify(experiments[key] ? `${key} agregado al plan` : `${key} removido del plan`); }); refresh(); });
setupTheme(); updateDashboard('all');
