const $ = (selector) => document.querySelector(selector);
const scenarios = {
  valid: { route: 'POST /api/leads', status: '201 Created', tone: 'success', meta: '18ms · requestId req_001', response: () => ({ data: { id: 'lead_demo_001', name: $('#name').value, email: $('#email').value, company: $('#company').value, source: $('#source').value, status: 'new' }, meta: { requestId: 'req_demo_001', idempotencyKey: 'idem_demo_001' } }) },
  invalid: { route: 'POST /api/leads', status: '422 Unprocessable Entity', tone: 'error', meta: '7ms · 3 fields to fix', response: () => ({ error: 'VALIDATION_ERROR', details: { email: ['Correo inválido o incompleto'], consent: ['El consentimiento debe ser true'], name: ['Mínimo 2 caracteres'] }, meta: { requestId: 'req_demo_002' } }) },
  duplicate: { route: 'POST /api/leads', status: '409 Conflict', tone: 'warning', meta: '12ms · idempotency replay', response: () => ({ error: 'DUPLICATE_LEAD', message: 'El lead ya existe para esta campaña.', data: { existingId: 'lead_1024', action: 'returned_existing' }, meta: { requestId: 'req_demo_003' } }) },
  list: { route: 'GET /api/leads?page=1&limit=3', status: '200 OK', tone: 'success', meta: '9ms · cache miss', response: () => ({ data: [{ id: 'lead_1024', name: 'Mariana Torres', status: 'qualified' }, { id: 'lead_1023', name: 'Carlos Méndez', status: 'proposal' }, { id: 'lead_1022', name: 'Sofía Lara', status: 'new' }], pagination: { page: 1, limit: 3, total: 24, hasNext: true } }) },
  health: { route: 'GET /health', status: '200 OK', tone: 'success', meta: '4ms · dependencies healthy', response: () => ({ status: 'ok', service: 'api-contract-studio', version: '1.0.0', checks: { memory: 'ok', repository: 'ok', crmQueue: 'degraded' }, timestamp: new Date().toISOString() }) }
};
let current = 'valid';
function run(name = current) { const scenario = scenarios[name]; current = name; $('#route').textContent = scenario.route; $('#status').textContent = scenario.status; $('#status').className = `status ${scenario.tone}`; $('#response-meta').textContent = scenario.meta; $('#response').textContent = JSON.stringify(scenario.response(), null, 2); document.querySelectorAll('[data-scenario]').forEach((button) => button.classList.toggle('active', button.dataset.scenario === name)); if (name === 'invalid') $('#consent').checked = false; if (name === 'valid') $('#consent').checked = true; }
document.querySelectorAll('[data-scenario]').forEach((button) => button.addEventListener('click', () => run(button.dataset.scenario)));
$('#send').addEventListener('click', () => run(current));
$('#copy').addEventListener('click', async () => { await navigator.clipboard?.writeText($('#response').textContent); $('#copy').textContent = 'Copiado ✓'; setTimeout(() => { $('#copy').textContent = 'Copiar JSON'; }, 1200); });
run();
