const $ = (selector) => document.querySelector(selector);
const scenarios = {
  valid: { route: 'POST /api/leads', status: '201 Created', tone: 'success', meta: '18ms · requestId req_001', response: () => ({ data: { id: 'lead_demo_001', name: $('#name').value, email: $('#email').value, company: $('#company').value, source: $('#source').value, status: 'new' }, meta: { requestId: 'req_demo_001', idempotencyKey: 'idem_demo_001' } }) },
  invalid: { route: 'POST /api/leads', status: '422 Unprocessable Entity', tone: 'error', meta: '7ms · 3 fields to fix', response: () => ({ error: 'VALIDATION_ERROR', details: { email: ['Correo inválido o incompleto'], consent: ['El consentimiento debe ser true'], name: ['Mínimo 2 caracteres'] }, meta: { requestId: 'req_demo_002' } }) },
  duplicate: { route: 'POST /api/leads', status: '409 Conflict', tone: 'warning', meta: '12ms · idempotency replay', response: () => ({ error: 'DUPLICATE_LEAD', message: 'El lead ya existe para esta campaña.', data: { existingId: 'lead_1024', action: 'returned_existing' }, meta: { requestId: 'req_demo_003' } }) },
  list: { route: 'GET /api/leads?page=1&limit=3', status: '200 OK', tone: 'success', meta: '9ms · cache miss', response: () => ({ data: [{ id: 'lead_1024', name: 'Mariana Torres', status: 'qualified' }, { id: 'lead_1023', name: 'Carlos Méndez', status: 'proposal' }, { id: 'lead_1022', name: 'Sofía Lara', status: 'new' }], pagination: { page: 1, limit: 3, total: 24, hasNext: true } }) },
  health: { route: 'GET /health', status: '200 OK', tone: 'success', meta: '4ms · dependencies healthy', response: () => ({ status: 'ok', service: 'api-contract-studio', version: '1.0.0', checks: { memory: 'ok', repository: 'ok', crmQueue: 'degraded' }, timestamp: new Date().toISOString() }) }
};
let current = 'valid';
let history = (() => { try { return JSON.parse(localStorage.getItem('api-contract-history')) || []; } catch { return []; } })();
function setupTheme() { const button = $('#theme-toggle'); const apply = (theme) => { document.body.dataset.theme = theme; button.querySelector('.theme-label').textContent = theme === 'dark' ? 'Claro' : 'Oscuro'; button.setAttribute('aria-pressed', String(theme === 'dark')); }; apply(localStorage.getItem('portfolio-demo-theme') || 'light'); button.addEventListener('click', () => { const next = document.body.dataset.theme === 'dark' ? 'light' : 'dark'; localStorage.setItem('portfolio-demo-theme', next); apply(next); }); }
function notify(message) { const node = document.createElement('div'); node.className = 'toast'; node.textContent = message; document.body.appendChild(node); setTimeout(() => node.remove(), 1800); }
function getRequest() { return { name: $('#name').value.trim(), email: $('#email').value.trim(), company: $('#company').value.trim(), source: $('#source').value, consent: $('#consent').checked }; }
function copyText(value) { if (navigator.clipboard?.writeText) return navigator.clipboard.writeText(value); const area = document.createElement('textarea'); area.value = value; document.body.appendChild(area); area.select(); document.execCommand('copy'); area.remove(); return Promise.resolve(); }
function renderHistory() { const target = $('#history-list'); target.innerHTML = history.length ? history.map((item) => `<button class="history-item" data-history="${item.id}" type="button"><strong>${item.status}</strong><span>${item.scenario} · ${item.time}</span></button>`).join('') : '<p class="history-empty">Aún no hay requests registrados.</p>'; document.querySelectorAll('[data-history]').forEach((item) => item.addEventListener('click', () => { const record = history.find((entry) => entry.id === item.dataset.history); if (record) { $('#response').textContent = JSON.stringify(record.response, null, 2); $('#response-meta').textContent = `${record.status} · historial`; } })); }
function syncRequest() { $('#request-json').textContent = JSON.stringify(getRequest(), null, 2); }
function run(name = current, record = true) { const scenario = scenarios[name]; current = name; const response = scenario.response(); $('#route').textContent = scenario.route; $('#status').textContent = scenario.status; $('#status').className = `status ${scenario.tone}`; $('#response-meta').textContent = scenario.meta; $('#response').textContent = JSON.stringify(response, null, 2); document.querySelectorAll('[data-scenario]').forEach((button) => button.classList.toggle('active', button.dataset.scenario === name)); if (name === 'invalid') $('#consent').checked = false; if (name === 'valid') $('#consent').checked = true; syncRequest(); if (record) { history = [{ id: `${Date.now()}`, scenario: name, status: scenario.status, time: new Date().toLocaleTimeString('es-MX', { hour: '2-digit', minute: '2-digit' }), response }, ...history].slice(0, 8); localStorage.setItem('api-contract-history', JSON.stringify(history)); renderHistory(); } }
function downloadResponse() { const content = $('#response').textContent; const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([content], { type: 'application/json' })); link.download = 'api-response.json'; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 0); notify('Response descargada'); }
setupTheme();
document.querySelectorAll('[data-scenario]').forEach((button) => button.addEventListener('click', () => run(button.dataset.scenario)));
document.querySelectorAll('#name,#email,#company,#source,#consent').forEach((field) => field.addEventListener('input', syncRequest));
$('#send').addEventListener('click', () => run(current));
$('#copy').addEventListener('click', async () => { await copyText($('#response').textContent); $('#copy').textContent = 'Copiado ✓'; setTimeout(() => { $('#copy').textContent = 'Copiar response'; }, 1200); });
$('#download').addEventListener('click', downloadResponse);
$('#reset').addEventListener('click', () => { $('#name').value = 'Aline Peña'; $('#email').value = 'aline@example.com'; $('#company').value = 'Portfolio Lab'; $('#source').value = 'website'; $('#consent').checked = true; run('valid', false); notify('Payload restablecido'); });
$('#clear-history').addEventListener('click', () => { history = []; localStorage.removeItem('api-contract-history'); renderHistory(); notify('Historial limpiado'); });
renderHistory(); run();
